sudo: false
language: go

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./gpg/

after_success:
  - bash <(curl -s https://codecov.io/bash)
