[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.9.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
