name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: ["windows-2019", "ubuntu-20.04", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    name: Tests (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Unit and coverage tests
        run: "go test -race -covermode=atomic -v ./gpg/"

  static_analysis:
    runs-on: ubuntu-20.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - name: Go fmt
        run: diff -u <(echo -n) <(gofmt -d -s *.go gpg/)
      - name: Go vet
        run: env GO111MODULE=on go vet ./...
      - name: Staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck -checks 'all,-ST1000' ./...
      - name: Gosec
        run: go run github.com/securego/gosec/cmd/gosec -exclude=G104 ./...

  policy_test:
    runs-on: ubuntu-20.04
    name: Test root vs reader policy access
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: innovationnorway/setup-vault@v1
      - run: ./scripts/test-policies.sh
