name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: ["windows-2019", "ubuntu-18.04", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    name: Tests (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-go@v2.1.2
        with:
          go-version: '^1.15.0'
      - name: Tests
        run: "go test -race -coverprofile='coverage.txt' -covermode=atomic -v ./gpg/"
      - uses: codecov/codecov-action@v1.0.13
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  api_test:
    runs-on: ubuntu-18.04
    name: Run Python API tests
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-go@v2.1.1
        with:
          go-version: '^1.15.0'
      - uses: innovationnorway/setup-vault@v1.0.2
      - uses: actions/setup-python@v2
      - name: Install Tox
        run: pip install tox
      - name: Run test script
        run: ./test.sh
  static_analysis:
    runs-on: ubuntu-18.04
    name: Run static analysis and linting
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-go@v2.1.2
        with:
          go-version: '^1.15.0'
      - name: Go fmt
        run: diff -u <(echo -n) <(gofmt -d -s *.go gpg/)
      - name: Go vet
        run: env GO111MODULE=on go vet ./...
      - name: Staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck -checks 'all,-ST1000' ./...
      - name: Gosec
        run: go run github.com/securego/gosec/cmd/gosec -exclude=G104 ./...
  build_script:
    runs-on: ubuntu-18.04
    name: Build across all supported architectures
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-go@v2.1.2
        with:
          go-version: '^1.15.0'
      - name: Build
        run: ./scripts/build.sh
      - name: Display checksum
        run: find ./pkg/ -name '*.sha256sum' -exec cat {} \;